SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

MIN_ASTEROID_RADIUS = 15
ASTEROID_DIVISIONS = 8
ASTEROID_SPAWN_INTERVAL = 0.8  # seconds
MAX_ASTEROID_RADIUS = MIN_ASTEROID_RADIUS * ASTEROID_DIVISIONS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 400
PLAYER_DECELERATION_MULTIPLIER = 0.3
PLAYER_BACKWARD_ACCELERATION = 0.75
PROJECTILE_SPEED = 500

SHOT_RADIUS = 5
