LARGURA_TELA = 1280
ALTURA_TELA = 720

MENOR_ASTEROID = 15
DIVISOES_ASTEROID = 8
TEMPO_DE_GERACAO_ASTEROID = 0.8  # em segundos
MAIOR_ASTEROID = MENOR_ASTEROID * DIVISOES_ASTEROID

TAMANHO_JOGADOR = 20
VELOCIDADE_GIRO = 300
VELOCIDADE_JOGADOR = 200
VELOCIDADE_PROJETIL = 500

TAMANHO_TIRO = 5