SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#asteroid sizes
MIN_ASTEROID_RADIUS = 20
ASTEROID_DIVISIONS = 6
MAX_ASTEROID_RADIUS = MIN_ASTEROID_RADIUS * ASTEROID_DIVISIONS

#asteroid spawn rate
ASTEROID_SPAWN_INTERVAL = 0.8  # seconds
MAX_MEDIUM_ASTEROIDS = 3

#player size
PLAYER_RADIUS = 20

#player movement
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 250
PLAYER_ACCELERATION = 400
PLAYER_DECELERATION_MULTIPLIER = 0.3
PLAYER_BACKWARD_ACCELERATION = 0.75

#player particles
PLAYER_THRUST_PARTICLE_RATE = 45
PLAYER_THRUST_IDLE_PARTICLE_RATE = 20
PLAYER_THRUST_PARTICLE_SPREAD = 35
PLAYER_THRUST_PARTICLE_BASE_OFFSET = 5

#shots
SHOT_RADIUS = 5
PROJECTILE_SPEED = 500
